// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://celkjcdirjzmaaksfohb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlbGtqY2Rpcmp6bWFha3Nmb2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyNDYzMTEsImV4cCI6MjA1MDgyMjMxMX0.-5jbuB7Gtv2yKKoETyoHGe6AuWbAPMbk2pxHMsVBGy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);